### ISSUE TITLE
subir los cambios a producción

### ISSUE THREAD

**Issue by nez** [vaquer/FormulariosGOB#3]
Hola @vaquer, sigo sin ver los cambios en producción, puedes subirlos de una vez por favor?

**Comment by vaquer** [comment]
Hola @nez ya pase a master los cambios, pero Julio es el que debe poner en producción o más bien el que tiene el acceso para ponerlo en producción. Le comento a Julio para que actualice la imagen Docker.

**Comment by vaquer** [comment]
@nez Es normal que al mandar el formulario solicite permisos para modificar un google doc?

**Comment by urkonn** [comment]
ya está en producción
