### ISSUE TITLE
el js se come los campos deshabilitados antes de mandar el formulario

### ISSUE THREAD

**Issue by nez** [vaquer/FormulariosGOB#4]
Hola @vaquer, hay un problema en donde el contenido de los campos que están `disabled` no se está mandando en las peticiones al google form.

Lo puedes replicar asi:
En los developer tools del navegador, te vas a network, puedes limpiarlo con el icono del tache antes de ponerle enviar. Una vez que le pones enviar, buscas `formResponse`, y ahi ves que en `Form Data` no aparece.

![screen shot 2016-07-14 at 5 54 28 pm](https://cloud.githubusercontent.com/assets/505449/16858425/518c74ee-49ec-11e6-8c90-5655ed475575.png)

**Comment by vaquer** [comment]
Hola @nez comprendo, dejame revisarlo.

**Comment by carlosmaya** [comment]
@vaquer si, es porque el input está como disabled y al hacer el POST no lo envía, una opción sería ponerlo hidden con el value, se me ocurre

![screen shot 2016-07-20 at 09 47 39](https://cloud.githubusercontent.com/assets/2633527/16990877/509ac352-4e5f-11e6-8452-191e8752db4c.png)
